name: arthur-genai-engine
services:
  db:
    image: postgres
    shm_size: 128mb
    environment:
      - POSTGRES_PASSWORD=changeme_pg_password
      - POSTGRES_DB=arthur_genai_engine
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5435:5432"
  genai-engine:
    # If you have GPUs, use `genai-engine-gpu` image instead
    image: arthurplatform/genai-engine-cpu:${GENAI_ENGINE_VERSION-latest}
    platform: linux/amd64
    depends_on:
      - db
    ports:
      - "3030:3030"
    environment:
      - POSTGRES_USER=postgres
      # Must match POSTGRES_PASSWORD in the db service
      - POSTGRES_PASSWORD=changeme_pg_password
      - POSTGRES_URL=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=arthur_genai_engine
      - POSTGRES_USE_SSL=false
      - ALLOW_ADMIN_KEY_GENERAL_ACCESS=enabled
      # The address you want to access the engine from (e.g. hostname, DNS)
      - GENAI_ENGINE_INGRESS_URI=http://localhost:3030
      - GENAI_ENGINE_ADMIN_KEY=changeme_genai_engine_admin_key
      # Key used for encrypting secrets, generate a random string if not using
      # the setup-and-start scripts to populate one in the .env file
      # openssl rand -base64 32
      # - GENAI_ENGINE_SECRET_STORE_KEY=changeme_secret_store_key
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "lsof", "-i", ":3030"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 300s
volumes:
  db_data:
