# Chart.yaml
apiVersion: v2
name: arthur-engine
version: 2.1.108
dependencies:
  - name: arthur-genai-engine
    version: 2.1.108
    repository: oci://ghcr.io/arthur-ai/arthur-engine/charts
  - name: arthur-ml-engine
    version: 2.1.108
    repository: oci://ghcr.io/arthur-ai/arthur-engine/charts
